# Generated by Django 5.0.2 on 2024-05-24 18:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumos', '0001_initial'),
        ('materiaprima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidosAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('C', 'Creado'), ('U', 'Actualizado'), ('D', 'Borrado')], max_length=1)),
                ('details', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('ref_pedido', models.IntegerField(unique=True, verbose_name='Referencia')),
                ('pedi_fecha', models.DateField(default=django.utils.timezone.now, verbose_name='fecha')),
                ('pedi_estado', models.CharField(choices=[('0', 'Completo'), ('1', 'Incompleto'), ('2', 'Rechazado')], max_length=1, verbose_name='estado')),
                ('pedi_comprobatePago', models.CharField(max_length=45, verbose_name='Comprobante Pago')),
                ('deleted', models.BooleanField(default=False)),
                ('pedi_insumos', models.ManyToManyField(blank=True, to='insumos.implementostrabajo')),
                ('pedi_materiaprima', models.ManyToManyField(blank=True, to='materiaprima.materiaprima')),
            ],
        ),
    ]
