# Generated by Django 5.0.2 on 2024-05-24 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0001_initial'),
        ('pedidos', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImplementosTrabajo',
            new_name='Insumos',
        ),
        migrations.RenameModel(
            old_name='ImplementosAudit',
            new_name='InsumosAudit',
        ),
        migrations.RenameField(
            model_name='insumosaudit',
            old_name='implementos',
            new_name='insumos',
        ),
    ]
