# Generated by Django 5.0.2 on 2024-05-29 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturas', '0003_initial'),
        ('pedidos', '0002_initial'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facturasaudit',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facturasaudit',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_logs', to='facturas.facturas'),
        ),
        migrations.AddField(
            model_name='facturasaudit',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_logs', to='pedidos.pedidos'),
        ),
        migrations.AddField(
            model_name='facturasaudit',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prov_logs', to='proveedores.proveedores'),
        ),
        migrations.AddField(
            model_name='facturas',
            name='fac_iva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.iva'),
        ),
    ]
