# Generated by Django 5.0.2 on 2024-06-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturas',
            name='fac_proveedor',
        ),
    ]
