# Generated by Django 5.0.2 on 2024-05-29 01:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('prov_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('nit', models.IntegerField(unique=True, verbose_name='NIT')),
                ('prov_nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('prov_telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProveedoresAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('C', 'Creado'), ('U', 'Actualizado'), ('D', 'Borrado')], max_length=1)),
                ('details', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
