# Generated by Django 5.0.2 on 2024-05-29 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiaprima', '0001_initial'),
        ('productoterminado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('equi_encargadoCocina', models.CharField(default='NULL', max_length=50, verbose_name='Nombre')),
                ('equi_encargadoEntrega', models.CharField(default='NULL', max_length=50, verbose_name='Nombre')),
                ('equi_calidad', models.CharField(choices=[('0', 'Aprobado'), ('1', 'No Aprobado')], default='0', max_length=1, verbose_name='estado')),
                ('equi_nombre', models.CharField(default='NULL', max_length=50, verbose_name='Nombre')),
                ('equi_check', models.CharField(choices=[('0', 'Aprobado'), ('1', 'No Aprobado')], default='0', max_length=1, verbose_name='estado')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Coccion',
            fields=[
                ('cocc_id', models.AutoField(primary_key=True, serialize=False)),
                ('cocc_cantidad_total', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('cocc_pesoPostProcesamiento', models.FloatField(default=0, verbose_name='Peso')),
                ('cocc_merma', models.FloatField(default=0, verbose_name='Merma')),
                ('cocc_tiempoCoccion', models.IntegerField(verbose_name='Tiempo de Coccion')),
                ('cocc_temperaturafinal', models.FloatField(verbose_name='Temperatura final')),
                ('cocc_check', models.CharField(choices=[('0', 'Aceptado'), ('1', 'Rechazado')], default='0', max_length=1, verbose_name='estado')),
                ('cocc_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productoterminado.productoterminado')),
            ],
        ),
        migrations.CreateModel(
            name='CoccionMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('coccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procesamiento.coccion')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiaprima.materiaprimagenerica')),
            ],
        ),
        migrations.CreateModel(
            name='Picado',
            fields=[
                ('pica_id', models.AutoField(primary_key=True, serialize=False)),
                ('pica_cantidad_total', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('pica_pesoPostProcesamiento', models.FloatField(default=0, verbose_name='Peso')),
                ('pica_merma', models.FloatField(default=0, verbose_name='Peso Merma')),
                ('pica_check', models.CharField(choices=[('0', 'Aprobado'), ('1', 'No Aprobado')], max_length=1, verbose_name='estado')),
                ('pica_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productoterminado.productoterminado')),
            ],
        ),
        migrations.CreateModel(
            name='PicadoMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiaprima.materiaprimagenerica')),
                ('picado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procesamiento.picado')),
            ],
        ),
    ]
