# Generated by Django 5.0.2 on 2024-05-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productoterminado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('equi_encargadoCocina', models.CharField(default='NULL', max_length=50, verbose_name='Nombre')),
                ('equi_encargadoEntrega', models.CharField(default='NULL', max_length=50, verbose_name='Nombre')),
                ('equi_calidad', models.CharField(choices=[('0', 'Aprobado'), ('1', 'No Aprobado')], default='0', max_length=1, verbose_name='estado')),
                ('equi_nombre', models.CharField(default='NULL', max_length=50, verbose_name='Nombre')),
                ('equi_check', models.CharField(choices=[('0', 'Aprobado'), ('1', 'No Aprobado')], default='0', max_length=1, verbose_name='estado')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Coccion',
            fields=[
                ('id_coccion', models.AutoField(primary_key=True, serialize=False)),
                ('cocc_cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('cocc_pesoMPposproceso', models.FloatField(default=0, verbose_name='Peso')),
                ('cocc_merma', models.FloatField(default=0, verbose_name='Peso Merma')),
                ('cocc_tiempoCoccion', models.TimeField(default=100)),
                ('cocc_temperaturafinal', models.FloatField(verbose_name='temperatura final')),
                ('cocc_check', models.CharField(choices=[('0', 'Aceptado'), ('1', 'Rechazado')], default='0', max_length=1, verbose_name='estado')),
                ('cocc_producto', models.ManyToManyField(blank=True, to='productoterminado.productoterminadogenerico')),
            ],
        ),
        migrations.CreateModel(
            name='Picado',
            fields=[
                ('cod_procesamiento', models.AutoField(primary_key=True, serialize=False)),
                ('pica_cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('pica_pesoMPposproceso', models.FloatField(default=0, verbose_name='Peso')),
                ('pica_merma', models.FloatField(default=0, verbose_name='Peso Merma')),
                ('pica_check', models.CharField(choices=[('0', 'Aprobado'), ('1', 'No Aprobado')], max_length=1, verbose_name='estado')),
                ('pica_producto', models.ManyToManyField(blank=True, to='productoterminado.productoterminadogenerico')),
            ],
        ),
    ]
