# Generated by Django 5.0.2 on 2024-05-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExistenciaMp',
            fields=[
                ('codigo', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Código')),
                ('cantidadIngresada', models.PositiveIntegerField(verbose_name='Cantidad Ingresada')),
                ('cantidadEgresada', models.PositiveIntegerField(verbose_name='Cantidad Egresada')),
            ],
        ),
    ]
