# Generated by Django 5.0.2 on 2024-06-03 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('existencias', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExistenciaMp',
        ),
    ]
