# Generated by Django 5.0.2 on 2024-05-29 03:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiaprima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_lote', models.CharField(editable=False, max_length=8, unique=True)),
                ('pt_cantidad', models.IntegerField()),
                ('pt_fechapreparacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Preparacion')),
                ('pt_fechavencimiento', models.DateField(verbose_name='Fecha Vencimiento')),
            ],
        ),
        migrations.CreateModel(
            name='ExistenciaPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exisPT_CantidadIngresada', models.IntegerField(verbose_name='Cantidad Ingresada')),
                ('exisPT_CantidadEgresada', models.IntegerField(verbose_name='Cantidad Egresada')),
                ('pt_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productoterminado.productoterminado')),
            ],
        ),
        migrations.CreateModel(
            name='EmpaqueProductoTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_pesoKg', models.FloatField(verbose_name='Peso Empaque')),
                ('emp_cantidadBolsas', models.IntegerField(verbose_name='Cantidad Bolsas')),
                ('pt_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productoterminado.productoterminado')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoTerminadoAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('C', 'Creado'), ('U', 'Actualizado'), ('D', 'Borrado')], max_length=1)),
                ('details', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productoterminado.productoterminado')),
                ('productoterminado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='productoterminado.productoterminado')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoTerminadoGenerico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_nombre', models.CharField(max_length=50, verbose_name='Nombre Producto Terminado')),
                ('pt_tipo', models.CharField(choices=[('0', 'Cocción'), ('1', 'Picado')], default=0, max_length=1, verbose_name='Tipo')),
                ('materiaPrimaUsada', models.ManyToManyField(to='materiaprima.materiaprimagenerica')),
            ],
        ),
        migrations.AddField(
            model_name='productoterminado',
            name='pt_nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productoterminado.productoterminadogenerico'),
        ),
        migrations.CreateModel(
            name='CaracteristicasOrganolepticasPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(max_length=50, verbose_name='Observaciones')),
                ('olor', models.BooleanField(default=False, verbose_name='Olor')),
                ('sabor', models.BooleanField(default=False, verbose_name='Sabor')),
                ('textura', models.BooleanField(default=False, verbose_name='Textura')),
                ('color', models.BooleanField(default=False, verbose_name='Color')),
                ('estado', models.CharField(choices=[('0', 'Aprobado'), ('1', 'No Aprobado')], default=0, max_length=1, verbose_name='Estado')),
                ('producto', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='productoterminado.productoterminadogenerico')),
            ],
        ),
        migrations.CreateModel(
            name='Vacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_bolsas_rechazadas', models.IntegerField(verbose_name='Cantidad Bolsas Rechazadas')),
                ('cantidad_bolsas_liberadas', models.IntegerField(verbose_name='Cantidad Bolsas Liberadas')),
                ('pt_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productoterminado.productoterminado')),
            ],
        ),
    ]
