# Generated by Django 5.0.2 on 2024-05-29 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productoterminado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicasorganolepticaspt',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productoterminado.productoterminado'),
        ),
    ]
