# Generated by Django 5.0.2 on 2024-05-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productoterminado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoterminadogenerico',
            name='pt_tipo',
            field=models.CharField(choices=[('0', 'Cocción'), ('1', 'Picado')], default=0, max_length=1, verbose_name='Tipo'),
        ),
    ]
