# Generated by Django 5.0.2 on 2024-06-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productoterminado', '0002_alter_caracteristicasorganolepticaspt_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoterminadogenerico',
            name='cantidad_total',
            field=models.IntegerField(default=0, verbose_name='Cantidad Total'),
        ),
    ]
